export enum Types {
  SAVE_HTML = 'SAVE_HTML',
  SELECT_ID = 'SELECT_ID',
  VISIBLE_COLOR = 'VISIBLE_COLOR',
  SELECT_SECTION = 'SELECT_SECTION',
  EDIT_TEXT = 'EDIT_TEXT',
  LIST_GROUP = 'LIST_GROUP',
  SAVE_HISTORY = 'SAVE_HISTORY',
  SAVE_HISTORY_INDEX = 'SAVE_HISTORY_INDEX',
}
